spring:
  application:
    name: Amica
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aiclientdemo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000
app:
  encrypt-key: ${APP_ENCRYPT_KEY:default-key-change-me-123456}  # 用于存储api密钥，对称加密，区别于BCrypt的只加密不解密
  salt: ${SALT:deadbeef}